### ISSUE TITLE
Change use of yamlargparse to jsonargparse since package name changed

### ISSUE THREAD

**Issue by mauvilsa** [japaf/foamgen#17]
I have added support for jsonnet files to yamlargparse which meant the name of the package no longer made sense. I have renamed it to jsonargparse since it supports two types of json supersets. This doesn't break this code since it will use the old package anyway. I create this issue just in case you want to take advantage of new features or bug fixes, then the code needs adapted.

**Comment by japaf** [comment]
Thanks for letting me know. I will look into that when I find some time.

**Comment by japaf** [comment]
Resolved by c1156f5041502354f12f755686cdb3890026e01b.
